# Generated by Django 4.1.7 on 2023-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattest',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
