# Generated by Django 3.2.16 on 2023-04-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattest',
            name='breeder',
        ),
    ]
