# Generated by Django 4.1.7 on 2023-04-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0002_cattest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattest',
            name='buyer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
